-- MySQL Script generated by MySQL Workbench
-- Fri Dec 17 01:04:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lojaonline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lojaonline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lojaonline` DEFAULT CHARACTER SET utf8 ;
USE `lojaonline` ;

-- -----------------------------------------------------
-- Table `lojaonline`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaonline`.`usuario` (
  `idusuario` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojaonline`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaonline`.`vendedor` (
  `idvendedor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojaonline`.`camisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaonline`.`camisa` (
  `idcamisa` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idcamisa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojaonline`.`videogame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaonline`.`videogame` (
  `idvideogame` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idvideogame`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojaonline`.`relogio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaonline`.`relogio` (
  `idrelogio` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idrelogio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojaonline`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaonline`.`produtos` (
  `idprodutos` INT NOT NULL,
  `camisa_idcamisa` INT NOT NULL,
  `videogame_idvideogame` INT NOT NULL,
  `relogio_idrelogio` INT NOT NULL,
  `vendedor_idvendedor` INT NOT NULL,
  PRIMARY KEY (`idprodutos`, `camisa_idcamisa`, `videogame_idvideogame`, `relogio_idrelogio`, `vendedor_idvendedor`),
  INDEX `fk_produtos_camisa1_idx` (`camisa_idcamisa` ASC) VISIBLE,
  INDEX `fk_produtos_videogame1_idx` (`videogame_idvideogame` ASC) VISIBLE,
  INDEX `fk_produtos_relogio1_idx` (`relogio_idrelogio` ASC) VISIBLE,
  INDEX `fk_produtos_vendedor1_idx` (`vendedor_idvendedor` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_camisa1`
    FOREIGN KEY (`camisa_idcamisa`)
    REFERENCES `lojaonline`.`camisa` (`idcamisa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_videogame1`
    FOREIGN KEY (`videogame_idvideogame`)
    REFERENCES `lojaonline`.`videogame` (`idvideogame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_relogio1`
    FOREIGN KEY (`relogio_idrelogio`)
    REFERENCES `lojaonline`.`relogio` (`idrelogio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_vendedor1`
    FOREIGN KEY (`vendedor_idvendedor`)
    REFERENCES `lojaonline`.`vendedor` (`idvendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojaonline`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojaonline`.`pedido` (
  `idpedido` INT NOT NULL,
  `valorTotal` VARCHAR(45) NOT NULL,
  `quantidadePedido` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `produtos_idprodutos` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `usuario_idusuario`, `produtos_idprodutos`),
  INDEX `fk_pedido_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_pedido_produtos1_idx` (`produtos_idprodutos` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `lojaonline`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_produtos1`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `lojaonline`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use lojaonline;
show tables;
select * from usuario;
select * from vendedor;
select * from pedido;
select * from produtos;
select * from camisa;
select * from videogame;
select * from relogio;

insert into usuario values (1, 'Hugo', 'hugo@gmail.com', 'teste1');

insert into camisa values (1, 'regata', 5);
insert into relogio values (1, 'Rolex', 3);
insert into videogame values (1, 'ps4', 4);

insert into vendedor values (1, 'vendedor0', 'vendedor0@gmail.com', 68515000);

insert into produtos values (1, 1, 1, 1, 1);



